calendar creation
Orealba/My-Calendar pull request #2
Opened 2022-11-11 19:28 UTC by Orealba

Created the base of the calendar.
![Captura de Pantalla 2022-11-11 a las 20 24 40](https://user-images.githubusercontent.com/92450839/201415566-359806ce-f6f3-4194-9968-4210218d0319.png)

2022-11-11 19:34 UTC, alejandroPardo requested changes

2022-11-11 19:34 UTC, alejandroPardo commented on src/Components/MyCalendar.css
> +.myCalendar__calendar {
Esta clase no se está usando. borrala o cambia el style por el classname en el calendar

2022-11-11 19:45 UTC, Orealba commented on src/Components/MyCalendar.css
> +.myCalendar__calendar {
vale, lo haré

2022-11-14 11:07 UTC, alejandroPardo approved these changes

2022-11-14 11:14 UTC, merged